---
version: '3.8'
services:
  mydb:
    image: mysql:5
    environment:
      MY_ROOT_PASSWORD: srinath
  mywordpress:
    image: wordpress
    ports:
      - 8888:80
    links:
      - mydb:mysql
...
